### ISSUE TITLE
Photos can't be sent.

### ISSUE THREAD

**Issue by byheaven** [LelouchHe/logseq-local-telegram-bot#3]
Text works perfectly. But nothing happens when sending a photo to the bot. Test with version 0.0.5

**Comment by byheaven** [comment]
Maybe it is possible to use the telegra.ph service to store the photos and just sent the link to logseq?

**Comment by LelouchHe** [comment]
Hi @byheaven, thanks for trying this plugin and helping point out this issue.

I have fixed this issue in the latest release (v0.0.7).

It happens due to CORS difference between dev plugin and prod plugin. I didn't notice this since I've been working on the dev version all the time. Thanks for the notice.

Due to the limit, it won't download the photo to local storage. Instead, it renders images from Telegram directly. So it might includes some network requests when rendering the photo.

Could you help take a try to see whether it fixes this issue?

Thanks

**Comment by byheaven** [comment]
It works properly now. Thank you!
BTW, is it possible to write the block with something like `![${caption}](${photoUrl})` so the photo can show up on mobile platforms too?

**Comment by LelouchHe** [comment]
Glad it works now!

Let me investigate this issue. Personally, I prefer markdown as well,  but I haven't found a way to do it yet.

I create a new issue to track this request. [Use markdown to render received photo](https://github.com/LelouchHe/logseq-local-telegram-bot/issues/4)

Hope this plugin will help you in your life! Thanks for your feedback!

**Comment by LelouchHe** [comment]
> 

Hi byheaven,

Do you mean on mobile Logseq? I'm afraid that the photo received can't be directly displayed as url, since Telegram file url generally expire in 1 day. I used "renderer" to get the latest url from its permanent file id to make sure the url is always valid.

So currently, there might not be a good way to walk around this problem.

BTW, if you have mobile Logseq installed, do you still prefer to use Telegram? Is it possible to copy/paste the photo directly there, like on desktop? I'm asking this because I don't have an eligible mobie device to try Logseq app, and that's part of the reasons I'm creating this plugin, since Telegram doesn't require the latest iOS version.

**Comment by byheaven** [comment]
My use case involves frequently sharing text and photos through the mobile app Telegram to Logseq, where I can collect and edit them later. Sometimes, I also edit these items on my iPad or iPhone, and then use Logseq to post them on Twitter or as an article. It would be helpful if photos being supported for this process. While it's possible to copy/paste photos directly into Logseq, it requires opening the app each time and waiting for all files to sync, which can take 10 seconds or more.

Thank you for explaining the limitations of the Telegram file URL expiration. I was wondering if it might be possible to add an option to manually pull a photo from a remote location on Telegram and save it locally. This way, users could choose to keep it without worrying about expiration and still be able to edit on their mobile device.

**Comment by LelouchHe** [comment]
> 

Hi byheaven, i have figured out a way to render photo on mobile with no plugin! See changes in this pr: https://github.com/LelouchHe/logseq-local-telegram-bot/pull/6. it's kind of hacky, but it should work.

as for saving photos, i only know that it can be done on desktop, but i'm not sure about mobile. If the plugin wants to do that, it might face the same CORS issue mentioned above. Better to ask Logseq official to add it on mobile, if they haven't done it already.

Anyway, let me finish that pr and rollout a new release soon. After that, I think you will be able to see photo on those mobile devices, if it works the same way as desktop. Do let me know after you try it.
